# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  DOCKER_REPO: martopad/myapp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build-type: [Release, Debug]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Env Variables
      run: |
        echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-7)
        echo ::set-env name=GITHUB_BUILD_DATE_FORMATTED::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Docker Build Myapp
      run: |
        docker build \
          --tag ${{ env.DOCKER_REPO }}:${{ env.GITHUB_SHA_SHORT }}-${{ matrix.build-type }} \
          --build-arg BUILD_DATE=${{ env.GITHUB_BUILD_DATE_FORMATTED }} \
          --build-arg BUILD_VERSION=${{ env.GITHUB_SHA_SHORT }} \
          --build-arg BUILD_TYPE=${{ matrix.build-type }} \
          .
    - name: Docker Run Myapp
      run: |
        docker run \
          --rm \
          --env DEPLOYER=CI \
          ${{ env.DOCKER_REPO }}:${{ env.GITHUB_SHA_SHORT }}-${{ matrix.build-type }} \
          CI-ID
        
    - name: Login to DockerHub
      uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD_ACCESS_TOKEN }}
          
    - name: push to DockerHub
      run: |
        docker push \
          ${{ env.DOCKER_REPO }}:${{ env.GITHUB_SHA_SHORT }}-${{ matrix.build-type }}
  
