# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Env Variables
      run: |
        echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
        echo ::set-env name=GITHUB_BUILD_DATE_FORMATTED::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    # Runs a single command using the runners shell
    - name: Docker Build Myapp
      run: |
        docker build \
          --tag myapp:${{ env.GITHUB_SHA_SHORT }}-release \
          --build-arg BUILD_DATE=${{ env.GITHUB_BUILD_DATE_FORMATTED }} \
          --build-arg BUILD_VERSION=${{ env.GITHUB_SHA_SHORT }} \
          --build-arg BUILD_TYPE=Release \
          .

    # Runs a set of commands using the runners shell
    - name: Docker Run Myapp
      run: |
        docker run \
          --rm \
          --env DEPLOYER=CI \
          myapp:${{ env.GITHUB_SHA_SHORT }}-release \
          CI-ID

    # - name: Run The App
    #   run: |
    #     export DEPLOYER="CI"
    #     ${GITHUB_WORKSPACE}/bin/Release/myapp testIDCI

    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: myappBinaries
    #     path: ./bin/Release/myapp

    # - name: Install the app
    #   run: |
    #     cd ${GITHUB_WORKSPACE}/bin/Release
    #     make install
