# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: CMake Configure
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/bin/Release
        cd ${GITHUB_WORKSPACE}/bin/Release
        cmake -DCMAKE_BUILD_TYPE=Release ${GITHUB_WORKSPACE}/app/

    # Runs a set of commands using the runners shell
    - name: Build The App
      run: |
        cd ${GITHUB_WORKSPACE}/bin/Release
        make myapp
        ls ${GITHUB_WORKSPACE}/bin/Release/

    - name: Run The App
      run: |
        echo ${GITHUB_WORKSPACE}/bin/Release
        echo ---------------------
        ls ${GITHUB_WORKSPACE}/bin/Release
        echo ---------------------
        file ${GITHUB_WORKSPACE}/bin/Release/myapp
        ls -l ${GITHUB_WORKSPACE}/bin/Release/
        ${GITHUB_WORKSPACE}/bin/Release/myapp

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myappBinaries
        path: ./bin/Release/myapp

    # - name: Install the app
    #   run: |
    #     cd ${GITHUB_WORKSPACE}/bin/Release
    #     make install
